#!/bin/bash

# Allow multiple scripts for a git single hook.

# Usage:
#   cd proj/.git/hooks/
#   mkdir {hook-name}.d/
#   mv {hook-name} {hook-name}.d/
#   ln -s /path/to/git-hookd {hook-name}

HOOK=$0
stdin=$(cat)

for script in $HOOK.d/*; do
    if [ -x $script ]; then
        echo "$stdin" | $script "$@"
    fi
done
