#!/bin/bash

unalias jst 2> /dev/null
unset -f jst
function jst() {
    if [[ $(juju version) == "2."* ]]; then
        juju status --color "$@"
    else
        juju status --format=tabular
    fi
}

unalias jpt 2> /dev/null
unset -f jpt
function jpt() {
    if [[ $(juju version) == "2."* ]]; then
        watch -tcn0.5 -- juju status --color "$@"
    else
        watch -tcn0.5 -- juju status --format=tabular
    fi
}

unalias jptt 2> /dev/null
unset -f jptt
function jptt() {
    watch -tcn0.5 'juju status --color -m "$(juju models --format=json | jq -r '\''.models | map(.name) | map(select(contains("test-") or contains("zaza-")))[0]'\'')" '"$*"
}

unalias jr-a 2> /dev/null
unalias jr-s 2> /dev/null
unset -f jr-a
function jr-a() {
    if [[ $(juju version) == "2."* ]]; then
        juju remove-application "$@"
    else
        juju remove-service "$@"
    fi
}
alias jr-s='jr-a'

alias dhx='juju dhx'
alias jr-m='juju remove-machine'
alias ja-r='juju add-relation'
alias jr-r='juju remove-relation'
alias ja-u='juju add-unit'
alias jr-u='juju remove-unit'
alias jam='juju add-model --config default-series=focal --config resource-tags=owner=johnsca --config test-mode=true --config automatically-retry-hooks=false --config logging-config="<root>=DEBUG"'
alias jscp='juju scp'

#proxy_opts=" --model-default juju-http-proxy='http://squid.internal:3128' --model-default juju-https-proxy='http://squid.internal:3128' --model-default juju-no-proxy='localhost,127.0.0.1,0.0.0.0,ppa.launchpad.net,launchpad.net,10.0.8.0/24'"
unalias jbs 2> /dev/null
unset -f jbs
function jbs() {
    name="$1"; shift
    if [[ -z "$1" || "$1" == --* ]]; then
        cloud="$name"
    else
        cloud="$1"; shift
    fi
    case "$cloud" in
        vsphere)
            extra_opts="--model-default datastore=vsanDatastore --model-default primary-network=VLAN_2764 --config caas-image-repo=rocks.canonical.com/cdk/jujusolutions"
            ;;
        google)
            extra_opts="--model-default container-networking-method=local --model-default fan-config="
            ;;
        *)
            extra_opts=""
            ;;
    esac
    #--model-default image-stream=daily \
    juju bootstrap "$cloud" "$name" \
        --bootstrap-constraints "cores=2 mem=4G" \
        --config test-mode=true \
        --config mongo-memory-profile=low \
        --model-default default-series=focal \
        --model-default resource-tags=owner=johnsca \
        --model-default test-mode=true \
        --model-default automatically-retry-hooks=false \
        --model-default logging-config="<root>=DEBUG" \
        $extra_opts \
        "$@"
}

function _jdm() {
    juju show-model "$1" | grep -q 'cloud: localhost'
    lxd=$?
    juju destroy-model --destroy-storage -y "$1"
    if (( lxd )); then
        lxc profile delete juju-"$1"
    fi
}

unset -f jdm
function jdm() {
    if [[ "$*" == "" ]]; then
        _jdm "$(juju models --format=json | jq -r '."current-model"')"
    else
        for model in "$@"; do
            _jdm "$model"
        done
    fi
}

unset -f unit
function _unit() {
    unit=$1
    shift
    if [[ -z "$unit" ]]; then
        # nothing specified, take first errored unit, or no filter
        unit="$(juju status | grep '/.*error' | cut -f1 -d' ' | tr -d '*' | head -n1)"
    elif ! echo "$unit" | grep -q '[-/]'; then
        # application name specified; take first errored unit or first unit
        units="$(juju status "$unit" | grep '/[0-9]')"
        unit="$(echo "$units" | grep 'error')"
        if [[ -z "$unit" ]]; then
            unit="$(echo "$units" | head -n1)"
        fi
        unit="$(echo "$unit" | cut -f1 -d' ' | tr -d '*')"
    fi
    echo -n "$unit"
}

unset -f _filter
function _filter() {
    unit="$(_unit "$1")"
    if [[ "$unit" == */* ]]; then
        unit="$(echo "unit-$unit" | tr '/' '-')"
    fi
    if [[ -n "$unit" ]]; then
        echo -n "-i $unit"
    fi
}

unalias jssh 2> /dev/null
unset -f jssh
function jssh {
    unit="$(resolve_leader "$1")"
    shift
    juju ssh "$unit" -o IdentitiesOnly=yes "$@"
}

unset -f jl
function jl() {
    if [[ -n "$1" && $1 != "-"* ]]; then
        set -- "-i" "$1" "${@:2}"
    fi
    if [[ $(juju version) == "2."* ]]; then
        color="--color"
    else
        color=""
    fi
    juju debug-log $color "$@"
}
unset -f jll
function jll() {
    if [[ -n "$1" && $1 != "-"* ]]; then
        set -- "-i" "$1" "${@:2}"
    fi
    if [[ $(juju version) == "2."* ]]; then
        color="--color"
    else
        color=""
    fi
    juju debug-log $color --replay "$@" | less -R +G -F
}

function jd() {
    if [[ -z "$CHARM_BUILD_DIR" ]]; then
        >&2 echo "CHARM_BUILD_DIR is not set"
        return 1
    elif [[ -z "$CBD" ]]; then
        CBD="$CHARM_BUILD_DIR"
    fi
    name=""
    charm="$1"
    shift
    if [[ "$charm" == "-n" ]]; then
        charm=""
        name="$1"
        shift
    fi
    if [[ -e layer.yaml ]]; then
        if [[ -z "$charm" ]]; then
            charm=$(yq e .name metadata.yaml)
        fi
        if [[ "$charm" != *: && -e "$CBD/$charm" ]]; then
            charm_path="./$(realpath --relative-to . "$CBD/$charm")"
            >&2 echo "Deploying from $charm_path"
            name="$charm"
            charm="$charm_path"
        fi
    else
        >&2 echo "Deploying from ."
        charm=.
    fi
    juju deploy "$charm" "$name" "$@"
}

function ju() {
    if [[ -z "$CHARM_BUILD_DIR" ]]; then
        >&2 echo "CHARM_BUILD_DIR is not set"
        return 1
    elif [[ -z "$JR" ]]; then
        JR="$(dirname "$CHARM_BUILD_DIR")"
    fi
    charm="$1"
    shift
    if [[ -z "$charm" ]]; then
        charm=$(yq e .name metadata.yaml)
    fi
    if [[ -e "$CBD/$charm" ]]; then
        charm_path="./$(realpath --relative-to . "$CBD/$charm")"
        >&2 echo "Upgrading from $charm_path"
    else
        >&2 echo "Unable to determine path for $charm"
        return
    fi
    errored_units="$(juju status --format=json | jq -r '.applications["'"$charm"'"].units | to_entries | map(select(.value["workload-status"].current == "error")) | map(.key) | .[]')"
    if [[ -n "$errored_units" ]]; then
        juju upgrade-charm --force-units "$charm" --path "$charm_path" "$@"
        for unit in $errored_units; do
            echo "Retrying hook on $unit"
            juju resolved "$unit"
        done
    else
        juju upgrade-charm "$charm" --path "$charm_path" "$@"
    fi
}

function js() {
    juju switch "$@"
    ~/.devhelpers/juju-machine-count > ~/.cache/juju-machine-count
}

function jcc() {
    mkdir -p "$HOME/juju/envs/$1/"{charms,layers,interfaces,bundles,builds}
    jcs~ "$@"
}

function jcs() {
    export JR="$HOME/juju/envs/$1"
    export CHARM_LAYERS_DIR="$JR/layers"
    export CLD="$CHARM_LAYERS_DIR"
    export CHARM_INTERFACES_DIR="$JR/interfaces"
    export CID="$CHARM_INTERFACES_DIR"
    export CHARM_BUILD_DIR="$JR/builds"
    export CBD="$CHARM_BUILD_DIR"
    export CHARM_CHARMS_DIR="$JR/charms"
    export CCD="$CHARM_CHARMS_DIR"
    export CHARM_OVERLAYS_DIR="$JR/overlays"
    export COD="$CHARM_OVERLAYS_DIR"
    export CHARM_BUNDLES_DIR="$JR/bundles"
    export CBND="$CHARM_BUNDLES_DIR"
}


unset -f juju-current-model
function juju-current-model {
    if [[ -n "$JUJU_MODEL" ]]; then
        echo "$JUJU_MODEL"
    else
        controller="$(juju controllers --format=json | jq -r '.["current-controller"]')"
        if [[ -z "$controller" ]]; then
            echo "-:-"
        else
            model="$(juju controllers --format=json | jq -r ".controllers[\"$controller\"][\"current-model\"]" | sed -e 's:^.*/::')"
            if [[ "$model" == "null" ]]; then
                model="-"
            #    machines="?"
            #    units="?"
            #else
            #    status="$(timeout 0.5 juju models | grep '\*')"
            #    if [[ -n "$status" ]]; then
            #        machines="$(echo "$status" | awk '{print $5}')"
            #        units="$(echo "$status" | awk '{print $6}')"
            #    else
            #        machines="?"
            #        units="?"
            #    fi
            fi
            echo "$controller:$model"
        fi
    fi
}


unset -f jcd
function jcd() {
    case "$1" in
        -i) cd "$JR"/interfaces || return; shift;;
        -b) cd "$JR"/bundles || return; shift;;
        -l) cd "$JR"/layers || return; shift;;
        -o) cd "$JR"/overlays || return; shift;;
        -c) cd "$JR"/charms || return; shift;;
         *) cd "$JR"/charms || return;;
     esac
     cd "$1" || return
}

unset -f jdest
function jdest() {
    if [[ $(juju version) == "2."* ]]; then
        controller=${1:-$(juju controllers --format=json | jq -r '."current-controller"')}
        juju destroy-controller --destroy-storage --destroy-all-models "$controller"
    else
        jenv=${1-$(juju switch)}
        juju destroy-environment -y "$jenv" "$@"
        ~/.devhelpers/juju-machine-count > ~/.juju/.machine-count &
    fi
}

function render-bundle() {
    bundle="${1:-bundle.yaml}"
    output="${2:-${bundle//.yaml/.png/}}"
    curl -d "$(cat "$bundle")" http://svg.juju.solutions/?output=png > "$output"
}

unset -f jdo
function jdo {
    juju run-action --wait "$@"
}

function jrun {
    if [[ $# == 1 ]]; then
        selector='--all'
    elif [[ "$1" == *'/'* ]]; then
        selector='--unit'
    else
        if [[ $(juju version) == "2."* ]]; then
            selector='--application'
        else
            selector='--service'
        fi
    fi
    juju run $selector "$@"
}

alias juju-secret='grep admin-secret ~/.juju/environments/`juju switch`.jenv | sed -e "s/  admin-secret: //"'

function pull-src {
    output=$(charm pull-source "$@")
    echo "$output"
    cd "$(echo "$output" | cut -d' ' -f4)" || return
    if git remote -v | grep -Eq 'github.com/juju(-solutions)?'; then
        git remote set-url origin "$(git remote -v | head -n1 | awk '{print $2}' | sed -e 's=https://github.com/=git@github.com:=')"
    fi
}

# compare two charm store revisions to see if they're the same entity
function comp-rev {
    if [[ "$(charm show "$1" hash)" == "$(charm show "$2" hash)" ]]; then
        echo Match
    fi
}

unset -f resolve_leader
function resolve_leader {
    unit="$1"
    if [[ "$unit" != */* || "$unit" == *"/leader" ]]; then
        app="${unit%/leader}"
        unit="$(juju status --format=json | jq -r '.applications["'"$app"'"].units | to_entries | map(select(.value.leader)) | map(.key) | .[]')"
    fi
    echo "$unit"
}

unset -f jdh
function jdh {
    unit="$(resolve_leader "$1")"
    shift
    juju ssh "$unit" 'echo "export TERM=xterm-256color; stty sane; reset" | sudo tee -a /root/.bashrc >> ~/.bashrc'
    juju debug-hooks "$unit" "$@"
}
