#!/bin/bash

controller="$(juju controllers --format=json | jq -r '.["current-controller"]')"
if [[ -n "$controller" ]]; then
    model="$(juju controllers --format=json | jq -r ".controllers[\"$controller\"][\"current-model\"]" | sed -e 's:^.*/::')"
    if [[ -n "$model" ]]; then
        juju models | grep '\*' | awk '{print $6}'
        exit 0
    fi
fi
echo "?"
